//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lagerprogramm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maschinen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maschinen()
        {
            this.Ersatzteile1 = new HashSet<Ersatzteile>();
        }
    
        public string Maschine { get; set; }
        public string Maschinennummer { get; set; }
        public Nullable<System.DateTime> Baujahr { get; set; }
        public string Hersteller { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ersatzteile> Ersatzteile1 { get; set; }
    }
}
